### ISSUE TITLE
Typo in base.py line 285

### ISSUE THREAD

**Issue by MarcelEckh** [alexismeneses/py-adxl345#4]
**base.py** >

at line 285:
`self.set_offset(offset_x, offest_y, offset_z)`

must be:
`self.set_offset(offset_x, offset_y, offset_z)`

Otherwise 
> "offest_y" is not defined

**Comment by alexismeneses** [comment]
Thanks for reporting.
It's been a looong time since I haven't used this project. But really pleased to know that it keeps being useful.

I've pushed a commit fixing it.

**Comment by MarcelEckh** [comment]
Cool, thank you!
